### ISSUE TITLE
Download the normal prediction mode

### ISSUE THREAD

**Issue by wuaixiang** [THU-LYJ-Lab/O2-Recon#3]
I can not download the normal prediction mode from than link.

**Comment by AlbertHuyb** [comment]
The oneDrive link shoud work. Maybe you could try again. Thanks.

https://connecthkuhk-my.sharepoint.com/personal/jiepeng_connect_hku_hk/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fjiepeng%5Fconnect%5Fhku%5Fhk%2FDocuments%2FGitHub%2FNeuRIS&ga=1
