### ISSUE TITLE
 Unable to download  the in-painted dataset

### ISSUE THREAD

**Issue by 1Emr** [THU-LYJ-Lab/O2-Recon#4]
The data set you provided cannot be downloaded

**Comment by micky-li-hd** [comment]
+1

**Comment by sarosijbose** [comment]
Yes, same here - the link is not shared yet

**Comment by AlbertHuyb** [comment]
Hello everyone! Thanks for your interest and patience. I finally uploaded the related data to [HuggingFace](https://huggingface.co/datasets/AlbertHuyb/O2-Recon/tree/main). Please visit the HuggingFace page and follow the instructions in our [ReadMe](https://github.com/THU-LYJ-Lab/O2-Recon/blob/main/README.md) file.
